name: compile-code-action
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  compile-main-program:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make
